### ISSUE TITLE
pretrain.py crashes and cannot identify images.

### ISSUE THREAD

**Issue by hardik124** [marco-c/autowebcompat#131] opened 2018-03-15 11:18 UTC
On running pretrain.py the following is the message : 

> cannot identify image file 'data/3277_5_chrome.png'
> cannot identify image file 'data/8016_2_firefox.png'
> cannot identify image file 'data/6928_chrome.png'
> cannot identify image file 'data/602_1_firefox.png'
> cannot identify image file 'data/9135_chrome.png'
> cannot identify image file 'data/7997_0_firefox.png'
> cannot identify image file 'data/7874_firefox.png'
> cannot identify image file 'data/8121_firefox.png'
> cannot identify image file 'data/2833_6_firefox.png'
> cannot identify image file 'data/5752_1_firefox.png'
> cannot identify image file 'data/1767_chrome.png'
> cannot identify image file 'data/1935_firefox.png'
> cannot identify image file 'data/10205_chrome.png'
> cannot identify image file 'data/10034_firefox.png'
> cannot identify image file 'data/5939_chrome.png'"" 
> 

```

And it crashes with the following stacktrace .

> Traceback (most recent call last):
>   File "pretrain.py", line 14, in <module>
>     image = utils.load_image(all_images[0])
>   File "/home/f390/autowebcompat/autowebcompat/autowebcompat/utils.py", line 80, in load_image
>     img = load_img(os.path.join(parent_dir, fname), target_size=(32, 24))
>   File "/usr/local/lib/python3.6/dist-packages/Keras-2.1.4-py3.6.egg/keras/preprocessing/image.py", line 362, in load_img
>   File "/home/f390/.local/lib/python3.6/site-packages/PIL/Image.py", line 2543, in open
>     fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'data_resized/3526_0_firefox.png'
>

**Comment by marco-c** [comment] 2018-03-15 11:20
Duplicate of #98.
Git LFS is required (see the Setup section in the documentation).

**Closed by marco-c** 2018-03-15 11:20 UTC

**Comment by hardik124** [comment] 2018-03-15 13:00
@marco-c  I have installed git lfs. And cloned the repo using git clone --recurse-submodules REPO_URL , Still I am getting this error.

**Comment by marco-c** [comment] 2018-03-15 13:03
What is the output of `cat data/8016_2_firefox.png`?

**Comment by hardik124** [comment] 2018-03-15 14:01
@marco-c  I am cloning the repo from scratch. I think it is due to git-lfs itself.
