### ISSUE TITLE
Downloading Images for training

### ISSUE THREAD

**Issue by vikasmahato** [marco-c/autowebcompat#99] opened 2018-03-02 08:05 UTC
I just forked and cloned the repository and ran the following commands as described in the README
1. pip3 install -r requirements.txt
2. pip3 install -r test-requirements.txt

But when I run `python3 pretrain.py`I get the following error

`/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from 'float' to 'np.floating' is deprecated. In future, it will be treated as 'np.float64 == np.dtype(float).type'.
  from ._conv import register_converters as _register_converters`

`Using TensorFlow backend.
Traceback (most recent call last):
  File "pretrain.py", line 14, in <module>
    image = utils.load_image(all_images[0])
IndexError: list index out of range`

This might be due to missing training images and I am unable to figure out how to download the training images

**Comment by Shashi456** [comment] 2018-03-02 08:07
@vikasmahato you need to run the get_dependencies.py script

**Comment by Shashi456** [comment] 2018-03-02 08:16
@vikasmahato  you need to run the get_dependencies.py script

**Comment by Shashi456** [comment] 2018-03-02 08:24
@marco-c I see that you have removed the get_dependencies script and also mentioned that you've moved tools to some other git repository. How do you suggest that we cover that step now, i.e download the data ? could we update the readme to mention that.

**Comment by vikasmahato** [comment] 2018-03-02 08:27
@Shashi456 Would it be fine if I chekout a previous version of autowebcompat
and use the get_dependencies.py script from there?

**Comment by Shashi456** [comment] 2018-03-02 08:28
@vikasmahato  for now i'm putting the old script of get_dependencies here , you should run this in your autowebcompat directory to download the images .

See the script [here](https://github.com/Shashi456/autowebcompat/blob/master/get_dependencies.py)

**Comment by vikasmahato** [comment] 2018-03-02 08:29
@Shashi456 Thanks a lot! :)

**Comment by marco-c** [comment] 2018-03-02 10:29
The data is stored in two git submodules, you just need to pull them too.
The submodules are using Git LFS, so you should install that too first.

Duplicate of #98.

**Closed by marco-c** 2018-03-02 10:29 UTC
